name: Continuous Integration and Delivery # workflow name

on:  # this is the entry point to the events, we specificy when the actions should be run
  push:
    branches: [main]  #specificy  which branch should the workflow be triggered
  pull_request:
    branches: [main] #specificy  which branch should the workflow be triggered

jobs:
  ci-cd-pax: # name of  the job
    runs-on: ubuntu-latest # specify that the app will run on the latest version of ubuntu
    steps: 
      - name: Executing remote  command and deployment to digital ocean for production environment
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.DROPLET_IP }}"
          USERNAME: "${{ secrets.DROPLET_USERNAME }}"
          PORT: 22
          KEY: ${{ secrets.DO_PRIVATE_KEY}}
          script: |
            source pax-env/bin/activate
            cd paxabale-webapp/
            git pull origin main
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart nginx
            sudo supervisorctl restart pax-unicorn
            
            


